/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keretaapi_dian.nofika;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DIAN NOFIKA P A
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pesan = new javax.swing.JButton();
        data = new javax.swing.JButton();
        cetaktiket = new javax.swing.JButton();
        cekharga = new javax.swing.JButton();
        harga = new javax.swing.JTextField();
        noidentitas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        combo5 = new javax.swing.JComboBox<>();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        eksekutif = new javax.swing.JRadioButton();
        ekonomi = new javax.swing.JRadioButton();
        combo3 = new javax.swing.JComboBox<>();
        combo4 = new javax.swing.JComboBox<>();
        tgl = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("PEMESANAN TIKET KERETA API");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 30, 400, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PEMESANAN TIKET KERETA API");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 0, 400, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 60);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 770, 10);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SEAT");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 370, 160, 30);

        pesan.setText("PESAN");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        jPanel2.add(pesan);
        pesan.setBounds(480, 210, 80, 40);

        data.setText("DATA");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        jPanel2.add(data);
        data.setBounds(480, 310, 80, 40);

        cetaktiket.setText("CETAK TIKET");
        jPanel2.add(cetaktiket);
        cetaktiket.setBounds(650, 340, 110, 40);

        cekharga.setText("CEK HARGA");
        cekharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekhargaActionPerformed(evt);
            }
        });
        jPanel2.add(cekharga);
        cekharga.setBounds(500, 100, 110, 23);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel2.add(harga);
        harga.setBounds(470, 150, 170, 30);
        jPanel2.add(noidentitas);
        noidentitas.setBounds(480, 40, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NO IDENTITAS");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(340, 40, 100, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Stasiun Tujuan");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 190, 160, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tanggal Keberangkatan");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 230, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Waktu Keberangkatan");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 270, 160, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("KELAS");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 310, 160, 30);
        jPanel2.add(nama);
        nama.setBounds(100, 40, 170, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Stasiun Keberangkatan");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 150, 160, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("NAMA");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 40, 60, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 80, 770, 10);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DATA PEMESAN");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 0, 110, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("DATA KEBERANGKATAN");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 90, 150, 30);

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel2.add(hapus);
        hapus.setBounds(480, 260, 80, 40);

        combo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SEAT--", "A", "B", "C" }));
        jPanel2.add(combo5);
        combo5.setBounds(310, 370, 100, 30);

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Stasiun Keberangkatan--", "Tulungagung", "Malang" }));
        jPanel2.add(combo1);
        combo1.setBounds(210, 150, 170, 30);

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Stasiun Tujuan--", "Tulungagung", "Malang" }));
        jPanel2.add(combo2);
        combo2.setBounds(210, 190, 170, 30);

        buttonGroup1.add(eksekutif);
        eksekutif.setText("EKSEKUTIF");
        jPanel2.add(eksekutif);
        eksekutif.setBounds(210, 340, 140, 23);

        buttonGroup1.add(ekonomi);
        ekonomi.setText("EKONOMI-AC");
        jPanel2.add(ekonomi);
        ekonomi.setBounds(210, 310, 140, 23);

        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--JADWAL--", "07.10", "10.25", "14.45" }));
        jPanel2.add(combo3);
        combo3.setBounds(210, 270, 170, 30);

        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--GERBONG--", "1", "2", "3", "4", "5" }));
        jPanel2.add(combo4);
        combo4.setBounds(210, 370, 100, 30);
        jPanel2.add(tgl);
        tgl.setBounds(210, 230, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 770, 410);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PT KAI - DAOP TULUNGGAUNG");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(280, 10, 190, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 60, 770, 40);

        setBounds(0, 0, 783, 549);
    }// </editor-fold>//GEN-END:initComponents

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        new data().show();
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        nama.setText("");
        noidentitas.setText("");
        combo1.setSelectedIndex(0);
        combo2.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        combo3.setSelectedIndex(0);
        combo4.setSelectedIndex(0);
        combo5.setSelectedIndex(0);
// TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void cekhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekhargaActionPerformed
        if (ekonomi.isSelected())
        {
            harga.setText("Rp. 15.000,00");
        } else if (eksekutif.isSelected()) {
            harga.setText("Rp. 85.000,00");
        } else {
            JOptionPane.showMessageDialog(null, "Pilih Kelas Kereta Api", "GAGAL", JOptionPane.INFORMATION_MESSAGE);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_cekhargaActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        if ("".equals(nama.getText()) || "".equals(noidentitas.getText()) || combo1.equals(0) || combo2.equals(0) || combo3.equals(0) || combo4.equals(0) || combo5.equals(0)) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "ERROR" , JOptionPane.WARNING_MESSAGE);
        } else {
            String Kls = "";
            String A   = "";
            String B   = "";
            String C   = "";
            String D   = "";
            String E   = "";
            if (ekonomi.isSelected()) {
                Kls = "Ekonomi-AC";
            } else if (eksekutif.isSelected()) {
                Kls = "Eksekutif";
            } else if (combo1.getSelectedIndex()==1){
                A = "Tulungagung";
            } else if (combo1.getSelectedIndex()==2) {
                A = "Malang";
            } else if (combo2.getSelectedIndex()==1){
                B = "Tulungagung";
            } else if (combo2.getSelectedIndex()==2){
                B = "Malang";
            } else if (combo3.getSelectedIndex()==1){
                C = "07.10";
            }  else if (combo3.getSelectedIndex()==2){
                C = "10.25";
            } else if (combo3.getSelectedIndex()==3){
                C = "14.45";
            } else if (combo4.getSelectedIndex()==1){
                D = "1";
            }else if (combo4.getSelectedIndex()==2){
                D = "2";
            }else if (combo4.getSelectedIndex()==3){
                D = "3";
            }else if (combo4.getSelectedIndex()==4){
                D = "4";
            }else if (combo4.getSelectedIndex()==5){
                D = "5";
            } else if (combo5.getSelectedIndex()==1){
                E = "A";
            } else if (combo5.getSelectedIndex()==2){
                E = "B";
            } else if (combo5.getSelectedIndex()==3){
                E = "C";
            }
            String SQL = "INSERT INTO `tb_data`(`nama`,`id`,`sb`,`st`,`tanggal`,`kelas`,`waktu`,`tempat`,`harga`) VALUES ('"+nama.getText()+"','"+noidentitas.getText()+"','"+A+"','"+B+"','"+tgl.getDate()+"','"+C+"','"+Kls+"','"+D+" "+E+"')";
            try {
                int status = KoneksiDB.execute(SQL);
                if (status == 1){
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "ERROR", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_pesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cekharga;
    private javax.swing.JButton cetaktiket;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JComboBox<String> combo5;
    private javax.swing.JButton data;
    private javax.swing.JRadioButton ekonomi;
    private javax.swing.JRadioButton eksekutif;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField noidentitas;
    private javax.swing.JButton pesan;
    private com.toedter.calendar.JDateChooser tgl;
    // End of variables declaration//GEN-END:variables
}
